SET FOREIGN_KEY_CHECKS = 0;

LOAD DATA LOCAL INFILE './prime-employees.csv' 
REPLACE INTO TABLE Employees
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

SHOW WARNINGS LIMIT 10;
SET FOREIGN_KEY_CHECKS = 1;


